### ISSUE TITLE
Реализовать автоматический импорт стилей

### ISSUE THREAD

**Issue by Sergio-Ka** [mmmnumber37/task1_resume#3]
Сделай так, чтобы у тебя в точке входа была бы функция, которая реквайрила твои стилевые файлы, файлы js, файлы картинок, чтобы не приходилось помнить о каждом модуле и подключать его вручную. Заодно исчезнут директивы @import в стилевых файлах. И тогда твое подключение блоков сведется к указанию include внутри pug-файлов, а остальное будет собираться само.

**Comment by Sergio-Ka** [comment]
Реализовал. Только у тебя импорт в начале файла index.js и это выглядит странным на фоне такой реализации. Можно попробовать сделать например как-то так:
```
const requireAllFiles = function requireAll(requireContext) {
  return requireContext.keys().map(requireContext);
};

requireAllFiles(require.context('./', true, /^\.\/.*\.(styl|png)$/));
```
Тогда у тебя вообще все файлы будут автоматом собираться по корневой папке и подпапкам, только типы нужно свои указать. И выглядеть короче будет.

**Comment by mmmnumber37** [comment]
Спасибо за реализацию. Я правильно понимаю, `png` и `svg` можно таким способом не импортировать потому, что они и так везде прописываются через `require`?

**Comment by Sergio-Ka** [comment]
По логике да. Но это где они у тебя в pug используются. Если через css вставляешь, там можно относительно ссылаться и в таком случае это пригождается, чтобы потом пути не менять. Там плагины есть всякие, которые пути могут резольвить автоматом. А вообще вебпак вроде такие проблемы сам разрешает, в смысле он видит реквайр в pug и в этой функции реквайр - но картинки не дублируются на выходе.
