### ISSUE TITLE
Блоки по БЭМ реализовавть миксинами pug

### ISSUE THREAD

**Issue by Sergio-Ka** [mmmnumber37/task1_resume#4]
Блоки по БЭМ должны быть реализованы миксинами pug. Параметры блоков должны передаваться объектами - в корневом блоке задаваться все параметры, внутри распределятся по более мелким блокам. То есть у проекта должна быть древовидная структура. Это требование компонентности верстки подобно подходу, применяемому в react. На риззоме есть требование по этому поводу во 2 задании и ссылка на статью.

**Comment by Sergio-Ka** [comment]
Гораздо лучше, но все еще не до конца. Есть следующий ряд замечаний:
1. Это есть микс:
```
    p.contact__item.contact__head= data.title
    a.contact__item.contact__content(href=`mailto:${ data.info }`)= data.info
```
По стандартам fsd микс не используется (кроме микса модификаторов) - и это единственное отличие для БЭМ от официального. Тот единственный случай когда нужен микс как правило - это позиционирование блоков. В данном случае блоки не должны влиять на свое окружение и как-то позиционироваться сами, вместо этого они помещаются в обертку, которая является элементом родительского блока и уже позиционирование задается ей.
2. Касательно блоков по БЭМ - они все должны быть вынесены в папки, то есть вот здесь:
```
        main.wrapper
            section.wrapper__column-left
```
У тебя должна быть папка wrapper в блоках и это должно быть в ней. А там как удобнее. Можно например сделать статичный миксин, который просто вызывается в index.pug, а уже в нем самом вызывать уже остальные миксины с их параметрами. И кстати тут вот это `wrapper__column-left` не просто элемент, а элемент с модификатором и должен он выглядеть тогда например так `wrapper__column.wrapper__column_position_left`. Для правого то же самое. На счет section тут кстати не уверен, так как он по идее по какому-то смыслу группировать должен, а там набор может быть совершенно разных блоков, поэтому тут это должен быть думаю div.
3. В таких местах нужно использовать декомпозицию объектов:
```
mixin logo (options)
    .logo
        img.logo__img(src=options.img alt="logo")
        .logo__name= options.name
        .logo__surname= options.surname
        .logo__profession= options.profession
```
то есть типа такого:
```
mixin logo (options = {name:"name", surname: "Petrov", profession: "frontender"})
    - let {name:"name", surname: "Petrov", profession: "frontender"} = options;
    .logo
        img.logo__img(src=options.img alt="logo")
        .logo__name= name
        .logo__surname= surname
        .logo__profession= profession
```
При таком подходе мы во-первых проверяем на то чтобы нам всякая ерунда в параметрах не упала (такое бывает при коммандной разработке, когда несколько человек пишут, что там кинет тебе в твой компонент другой прогер пусть будет на его совести, а ты должен предусмотреть ситуацию), во вторых мы задаем дефолтные значения (которые к слову могут быть пустыми, то есть "") и в-третьих мы внутри миксина обращаемся к переменным по более коротким именам. Здесь это не существенно, но если у тебя большой компонент и в нем много использований одной и той же переменной - экономия кода на лицо.  Задача как раз и научится, выработать навыки чтобы такое написание было на автомате. Посмотреть во всем проекте и переделать. Кстати бывает такое что внутри options может быть еще объект, ка кнапример у тебя там где-то data есть, тут тоже можно декомпозировать в одно строке типа так:
```
 - let {data: {name:"name", surname: "Petrov"}, profession: "frontender"} = options;
```
И у тебя тогда name и surname тоже будут доступны по короткому имени.

**Comment by mmmnumber37** [comment]
Если я правильно понял, то каждый `contact-item` в `contact` должен оборачиваться в обертку для позиционирования. Вытекающий вопрос: может ли знать блок родитель о классах дочернего блока?

**Comment by Sergio-Ka** [comment]
>Если я правильно понял, то каждый contact-item в contact должен оборачиваться в обертку для позиционирования. Вытекающий вопрос: может ли знать блок родитель о классах дочернего блока?

Нет такого понятия "дочерний блок" в методологии БЭМ. Если имеется в виду вложенные блоки - то блоки при любом раскладе не зависимые и друг о друге в любом направлении знать не должны. Но блок может знать о своих элементах. Обертка и есть элемент блока (того блока который включает в себя другой блок, то есть в твоих терминах - родительского), в который вкладывается например другой независимый блок. И обертке (элементу) может задаваться поведение, то есть свойства margin, padding, width ограничиваться например или height, хотя последнего лучше избегать, высота должна быть от контента плюс отступы. Да и с шириной не все всегда просто.

**Comment by Sergio-Ka** [comment]
Тут еще ряд замечаний:
1.  в profile жирный текст - это тоже отдельный параметр блока. Это сделано специально в макете. С тегом `<b>` плохо сделано. Там внутри самого блока profile на какой-нибудь span, который тоже будет элементом блока profile нужно повесить стили жирного текста через соответствующий класс. Только тут с именование класса подумать, что то типа "выделенный текст" элемент назвать, а не просто text__font-bold или что-то в этом духе. Тут достаточно простое решение.
2. Заголовки блоков тоже лучше передавать параметром, а не жестко зашивать их внутри блоков. Оно понятно что блок он и есть блок, но даже тривиальная задача переименовать какой-нибудь software в soft (при том что смысл блока сохраняется) обернется в необходимость лазить по кишкам блока вместо того чтобы ему параметр просто передать.
