### ISSUE TITLE
Семантика

### ISSUE THREAD

**Issue by Sergio-Ka** [mmmnumber37/task1_resume#6]
В стандартах [есть требования на тему семантики](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/semantic.md). Теги должны использоваться в соответствии со своим назначением. Например, тег `<p>` это абзац текста а не просто блочный элемент как это сделано в event.mix.pug. `<h1>` это заголовок и должен быть один на странице вообще. А в logo.pug он минимум дважды виден. Кроме того это явно не заголовки. То же самое касается `<h3>` в блоке контактов - там это тоже не заголовки как таковые. В том же контакте намешано aticle и section что явно избыточно и едва ли семантично. Достаточно блок сделать section, а внутри просто обычные div (или иное если семантично). Просмотри весь проект на предмет семантичности. И не надо перебарщивать с тегами, тут не тот случай когда кашу маслом не испортишь.

**Comment by mmmnumber37** [comment]
В вопросе семантики, меня постоянно путают `<section>` и `<article>`. И [требования на тему семантики](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/semantic.md) еще больше вносят путаницу в понимание (п.8 пример 3 разве не `<aside>` нужно использовать для боковых колонок, [взято отсюда](https://html5book.ru/html5-semantic-elements/) ). Оттуда же я черпаю понимание, что `<article>` - это обертка для группирование статей, а `<section>` - это обертка для группирования тематического содержимого. Если вам не сложно могли бы вы указать, что можно считать статьей в макете, а что группой тематического содержимого. Или я что-то не понимаю?

**Comment by mmmnumber37** [comment]
`<article>` - это обертка для группирование статьи

**Comment by Sergio-Ka** [comment]
По сути и там и там написано примерно одно и то же. НА сколько мне понимается - секция зависма от страницы и используется для группировки смысловых блоков на странице, если страница собой представляет единое смысловое целое. А статья не зависит от остальной страницы и по большому счету ее можно тупо выдернуть и применить в другом месте где-то. В данном проекте я думаю все 7 блоков это section.

**Comment by Sergio-Ka** [comment]
А основные вопросы в рамках данного issue были с тем, что явно излишнее использование тэгов и не семантичное. Например про тег `<p>` я писал уже, но вот здесь например он используется:
```
        .contact__info
            each data in options.data
                section.contact__row
                    if data.isEmail
                        p.contact__item.contact__head= data.title
                        a.contact__item.contact__content(href=`mailto:${ data.info }`)= data.info
                    else if data.isPhone
```
Но это явно не абзацы текста, а значит здесь эти теги не нужны.
Здесь:
```
section.event
        .event__circle
        header.event__head
            h3.event__title(class=`${ options.theme == 'education'? 'event__title--color-blue': '' }`)= options.title
            span.event__date= `// ${ options.date }` 
        .event__desc= options.desc
        .event__content!= options.text 
```
Тоже кажется сомнительным использование как тега header так и h3. Это по факту пункты листа и тег `<li>` здесь смотрелся бы даже уместнее.
Ну и так далее. Нужно посмотреть весь проект на эту тему. Основная часть тегов, которая должна быть -  это обычный `<div>`, а остальные теги - это акценты для поисковиков и для всяких автоматизированных средств обработки по типу средств чтения для слепых.

**Comment by mmmnumber37** [comment]
Спасибо за внесение ясности в этот вопрос :)
