### ISSUE TITLE
Теги с классами

### ISSUE THREAD

**Issue by Sergio-Ka** [mmmnumber37/task1_resume#8]
Все теги должны быть с классами ([html.тэги.п11](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78iae/)). Здесь тег img голый. Посмотри во всем проекте.
```
mixin title-resume (options)
    header.title-resume
        .title-resume__img
            img(src=options.img, alt=options.title)
        h2.title-resume__text= options.title
        hr.title-resume__line
```

**Comment by mmmnumber37** [comment]
29f0742

**Comment by mmmnumber37** [comment]
Исправил здесь 29f0742

**Comment by Sergio-Ka** [comment]
Когда делаешь коммиты в git, там в теле указываешь #номер_issue, тогда коммиты будут подтягиваться в issue автоматом, типа так: `git commit -m "#8 fix-tags-with-classes"`

**Comment by Sergio-Ka** [comment]
Можно закрыть этот issue.
